seed: 1234
dataset: "planning-datasets/data/sdd/s064_0.5_128_300/bookstore/"
logdir: "model"
Tmax: 0.25

encoder:
  input: "rgb+"
  arch: "Unet"
  depth: 3
  const: 10.0

params:
  batch_size: 10
  num_epochs: 10
  lr: 0.001


hydra:
  job:
    chdir: False
