seed: 1234
dataset: "src/neural_astar/utils/voronoi_utilities/maps_data/maps"
logdir: "model"
Tmax: 0.25


encoder:
  input: "m+"
  arch: "CNN"
  depth: 4


params: 
  batch_size:  8
  num_epochs: 50
  lr: 0.001


hydra:
  job:
    chdir: False