seed: 1234
dataset: "src/maps_npz"
logdir: "model/voronoi"
Tmax: 0.035


encoder:
  input: "m+"
  arch: "CNN"
  depth: 3


params: 
  batch_size: 5
<<<<<<< HEAD
  num_epochs: 50
=======
  num_epochs: 20
>>>>>>> 3437debecc8b8672c0384086673f815e3198a85a
  lr: 0.01



hydra:
  job:
    chdir: False