seed: 1234
dataset: "src/maps_npz"
logdir: "model/voronoi"
Tmax: 0.25


encoder:
  input: "m+"
  arch: "CNN"
  depth: 4


params: 
  batch_size: 5
  num_epochs: 30
  lr: 0.001


hydra:
  job:
    chdir: False